logging:
  level: INFO
  loggers:
    com.khoros: DEBUG
server:
  applicationConnectors:
    - type: http
      port: 9090
  adminConnectors:
    - type: http
      port: 9093

elasticsearchConfiguration:
  host: localhost
  port: 9500
